version: 2.1
orbs:
  docker: circleci/docker@0.6.1
jobs:
  push_docker:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: lolgab/scala-native-docker
      - docker/push:
          image: lolgab/scala-native-docker
workflows:
  build:
    jobs:
      - push_docker:
          filters:
            branches:
              only:
                - master
